Repository egc-L5/decide-single-joaquin1, pull requests merged in 2023-12, with the labels that each got.

#50 refactor: Elimina workflows redundantes #48
  .github/workflows/Django-testing.yml
  .github/workflows/django.yml
Labels: refactor

#47 test: Añadidos tests de Censo tras aplicar cambios #33
  decide/census/tests.py
Labels: test

#53 M3 Pruebas de Importar Censos
  decide/census/tests.py
  decide/census/views.py
Labels: test

#54 M3 Pruebas de Reutilización de censos
  decide/voting/templates/reuse_census.html
  decide/voting/tests.py
Labels: test

#52 fix: Traducciones eliminadas #Closes 27
  decide/booth/templates/booth/booth.html
  decide/decide/settings.py
  decide/decide/urls.py
  decide/locale/es/LC_MESSAGES/django.po
  decide/templates/admin/base_site.html
  decide/visualizer/templates/visualizer/visualizer.html
Labels: bug

#58 M3 Mejora de Interfaz de Importación de Censos
  decide/census/templates/import_census.html
  decide/census/tests.py
  decide/census/views.py
Labels: style

#60 test: crea tests vista exportación
  decide/census/tests.py
Labels: test

#69 feat: Limita acceso importaciones Closes #67
  decide/census/tests.py
  decide/census/views.py
  decide/local_settings.py
Labels: feat, conf, refactor, test

#57 M3 Releases automáticas
  .github/workflows/Django-CI.yml
  .github/workflows/releases.yml
Labels: conf

#71 feat: Despliegue de proyecto
  .github/workflows/Django-CI.yml
  .github/workflows/django.yml
  .github/workflows/releases.yml
  .gitignore
  .gitmessage.txt
  README.md
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/build.sh
  decide/census/admin.py
  decide/census/migrations/0004_remove_census_has_voted_remove_census_locality_and_more.py
  decide/census/migrations/0005_remove_census_status_remove_census_total_voters.py
  decide/census/models.py
  decide/census/templates/import_census.html
  decide/census/tests.py
  decide/census/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/local_settings.py
  decide/locale/es/LC_MESSAGES/django.po
  decide/templates/admin/base_site.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/admin.py
  decide/voting/forms.py
  decide/voting/models.py
  decide/voting/templates/reuse_census.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
  requirements.txt
Labels: feat

#72 fix: Error en el build.sh para despliegue
  decide/build.sh
Labels: bug

#73 fix: Error en el settings.py con las variables de entorno
  .github/workflows/Django-CI.yml
  decide/decide/settings.py
  requirements.txt
Labels: bug

#76 style: pantallas para las preguntas
  .github/workflows/Django-CI.yml
  decide/base/templates/base.html
  decide/voting/templates/question_add.html
  decide/voting/templates/question_list.html
Labels: style

#77 feat: implementación de preguntas si/no
  .github/workflows/Django-CI.yml
  decide/voting/forms.py
  decide/voting/migrations/0005_question_question_type.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: feat

#80 test: unitarios para crear y borrar preguntas
  decide/voting/tests.py
Labels: test

#84 refactor: Cambio de cabecera para revisión de M3
  decide/census/templates/export_census.html
Labels: refactor

#85 fix: Soluciona Error de CSRF Token #67
  decide/census/templates/import_census.html
  decide/census/tests.py
  decide/census/views.py
Labels: bug

#81 doc: diario de equipo actualizado
  decide/decide/settings.py
  doc/diario-de-equipo.md
Labels: doc

#82 test: Tests de Selenium para Reutilización de censo
  decide/voting/tests.py
Labels: test

#88 style: Añade estilos a la vista de reutilización de censo
  decide/voting/models.py
  decide/voting/templates/reuse_census.html
Labels: style

#90 feat: exporta censo a xml
  decide/census/templates/export_census.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
Labels: feat, test

#91 feat: Implementa Importacion de Censos en XML
  decide/census/templates/import_census.html
  decide/census/tests.py
  decide/census/views.py
Labels: feat, test

#92 Pre-release 2.0.0
  decide/base/templates/base.html
  decide/census/templates/export_census.html
  decide/census/templates/import_census.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/voting/forms.py
  decide/voting/migrations/0005_question_question_type.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/templates/question_add.html
  decide/voting/templates/question_list.html
  decide/voting/templates/reuse_census.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
  doc/diario-de-equipo.md
  docker/Dockerfile
Labels: doc, feat, conf, style, test

#95 conf: Borra archivo .vscode
  .vscode/launch.json
Labels: conf

#96 conf: Error de nombre en el workflow de releases
  .github/workflows/releases.yml
Labels: conf, refactor

#99 conf: Crea nuevo workflow de releases
  .github/workflows/Django-Releases.yml
  decide/census/templates/export_census.html
Labels: conf

#101 fix: Realiza Cambio M3-Defesna #100
  decide/voting/templates/question_list.html
Labels: bug, style
