Repository egc-L5/decide-single-joaquin1, pull requests merged in 2023-11, with the labels that each got.

#25 Tarea-501: Traduccion al ESP y multilenguaje
  decide/booth/templates/booth/booth.html
  decide/decide/settings.py
  decide/decide/urls.py
  decide/locale/es/LC_MESSAGES/django.po
  decide/templates/admin/base_site.html
  decide/visualizer/templates/visualizer/visualizer.html
  requirements.txt
Labels: enhancement

#29 Tarea-204: Añadir filtros y grupos a censos
  decide/census/admin.py
  decide/census/migrations/0002_census_locality_census_sex.py
  decide/census/migrations/0003_census_has_voted_census_vote_date_census_vote_method_and_more.py
  decide/census/models.py
  decide/census/views.py
  decide/local_settings.py
  requirements.txt
Labels: enhancement

#35 Tarea-303. Importar censo en formato XLSX
  decide/census/templates/import_census.html
  decide/census/views.py
Labels: enhancement

#34 Tarea-502. Integración de todo el código realizado para el M2
  decide/booth/templates/booth/booth.html
  decide/census/admin.py
  decide/census/migrations/0002_census_locality_census_sex.py
  decide/census/migrations/0003_census_has_voted_census_vote_date_census_vote_method_and_more.py
  decide/census/models.py
  decide/census/templates/export_census.html
  decide/census/templates/import_census.html
  decide/census/urls.py
  decide/census/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/local_settings.py
  decide/locale/es/LC_MESSAGES/django.po
  decide/templates/admin/base_site.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/views.py
  requirements.txt
Labels: enhancement

#46 M3 export census tests
  decide/census/tests.py
  decide/census/views.py
Labels: testing

#49 M3 ci coverage Closes#48
  .github/workflows/Django-CI.yml
Labels: configuration
